### ISSUE TITLE
/dev/ttyUSB0 device name

### ISSUE THREAD

**Issue by bidasknakayama** [ntamas/aio-usb-hotplug#5]
Hello !

Your app is nice : )
How to get the serial name /dev/ttyUSB0 or /dev/ttyUSB1
without it,, I could not use it...

Please help me.

**Comment by ntamas** [comment]
This is outside the scope of `aio-usb-hotplug`; `aio-usb-hotplug` gives you a `libusb` device object, and not all USB devices are serial ports. You need to find some other means to enumerate all serial port devices on your machine and map them back to the `device` object that you were given here.

If you are using `pyserial`, there's a [tool](https://pythonhosted.org/pyserial/tools.html#module-serial.tools.list_ports) that lists all serial ports. It gives you triplets of port names, descriptions and hardware IDs (typically vendor and product ID). If I were you, I would probably just use the events from `aio-usb-hotplug` to get notified when _something_ happened (a USB device was connected or disconnected), and then just look at the list of serial ports from `pyserial` to figure out what changed.
